### ISSUE TITLE
Some addresses cannot be encodded to public address

### ISSUE THREAD

**Issue by bkmeneguello** [icarusglider/PyRai#2]
I'm trying to encode all addresses from RaiBlocks database, but some of them fail with
```
Traceback (most recent call last):
  File "/home/rai/PyRai/pyrai.py", line 160, in <module>
    main()
  File "/home/rai/PyRai/pyrai.py", line 164, in main
    print(account_xrb(h))
  File "/home/rai/PyRai/pyrai.py", line 62, in account_xrb
    h.update(account.bytes)
  File "/usr/local/lib/python3.5/dist-packages/bitstring.py", line 1347, in _getbytes
    raise InterpretError("Cannot interpret as bytes unambiguously - "
bitstring.InterpretError: Cannot interpret as bytes unambiguously - not multiple of 8 bits.

Process finished with exit code 1
```

[This](https://github.com/icarusglider/PyRai/files/1594872/invalid.txt) are the HEX addresses this error occurs

**Comment by ghost** [comment]
there is something wrong with the hex addresses in your list. public keys are supposed to be 64 hex characters (32 bytes). Keys in your list are either 61 or 63 characters.

**Comment by bkmeneguello** [comment]
I fetched all frontiers from my local database using the RPC endpoint. But I never used this again, so I'll close it, probably was some mistake I made
